# Generated by Django 3.2.4 on 2021-09-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enable', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=-1)),
                ('street', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'Parking',
                'ordering': ['id'],
            },
        ),
    ]
