# Generated by Django 3.2.4 on 2021-09-04 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='parking',
            table='PPV_Parking',
        ),
    ]
