# Generated by Django 3.2.4 on 2021-09-11 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_parking_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='is_enable',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='street',
        ),
        migrations.AddField(
            model_name='parking',
            name='ID_Landlord',
            field=models.UUIDField(default='05be6df9-63fb-498a-b21d-550724b510e7'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parking',
            name='Location',
            field=models.CharField(default='Appenzell', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parking',
            name='PricePerHour',
            field=models.DecimalField(decimal_places=2, default=5.5, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parking',
            name='Street',
            field=models.TextField(default='Rinkenbach'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parking',
            name='StreetNo',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parking',
            name='ZIP',
            field=models.IntegerField(default=9050),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Renter', models.UUIDField()),
                ('DateTimeFrom', models.DateTimeField()),
                ('DateTimeTo', models.DateTimeField()),
                ('ID_Parking', models.ForeignKey(db_column='ID_Parking', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Parking', to='api.parking')),
            ],
            options={
                'db_table': 'PPV_Reservation',
                'ordering': ['id'],
            },
        ),
    ]
