# Generated by Django 3.2.4 on 2021-09-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210911_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='StreetNoSuffix',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
