# Generated by Django 3.2.4 on 2021-09-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_parking_streetnosuffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='IsCanceled',
            field=models.BooleanField(default=False),
        ),
    ]
