# Generated by Django 3.2.4 on 2021-09-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_reservation_iscanceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='Amount',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='PricePerHour',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=5),
            preserve_default=False,
        ),
    ]
